[enums]
# mode = n  [ positive n means strip n elements of the name from the front ]
# mode = -n [ negative n means keep n elements of the name from the end ]
HAPI_PartType = { rename = "auto", mode = -1 }
HAPI_License = { rename = "auto", mode = -2 }
HAPI_StatusType = { rename = "auto", mode = -2 }
HAPI_StatusVerbosity = { rename = "auto", mode = -1 }
HAPI_Result = { rename = "HapiResult", mode = 2 }
HAPI_SessionType = { rename = "auto", mode = -1 }
HAPI_State = { rename = "auto", mode = 2 }
HAPI_PackedPrimInstancingMode = { rename = "auto", mode = -1 }
HAPI_Permissions = { rename = "auto", mode = -2 }
HAPI_RampType = { rename = "auto", mode = -1 }
HAPI_ParmType = { rename = "auto", mode = 2 }
HAPI_PrmScriptType = { rename = "auto", mode = -2 }
HAPI_ChoiceListType = { rename = "auto", mode = -1 }
HAPI_PresetType = { rename = "auto", mode = -1 }
HAPI_GroupType = { rename = "auto", mode = -1 }
HAPI_AttributeOwner = { rename = "auto", mode = -1 }
HAPI_CurveType = { rename = "auto", mode = -1 }
HAPI_VolumeType = { rename = "auto", mode = -1 }
HAPI_VolumeVisualType = { rename = "auto", mode = -1 }
HAPI_StorageType = { rename = "auto", mode = -1 }
HAPI_AttributeTypeInfo = { rename = "auto", mode = -1 }
HAPI_GeoType = { rename = "auto", mode = -1 }
HAPI_InputType = { rename = "auto", mode = -1 }
HAPI_CurveOrders = { rename = "auto", mode = -1 }
HAPI_TransformComponent = { rename = "auto", mode = -1 }
HAPI_RSTOrder = { rename = "auto", mode = -1 }
HAPI_XYZOrder = { rename = "auto", mode = -1 }
HAPI_ImageDataFormat = { rename = "auto", mode = -1 }
HAPI_ImagePacking = { rename = "auto", mode = -1 }
HAPI_EnvIntType = { rename = "auto", mode = -2 }
HAPI_SessionEnvIntType = { rename = "auto", mode = -1 }
HAPI_CacheProperty = { rename = "auto", mode = -2 }
HAPI_HeightFieldSampling = { rename = "auto", mode = -1 }
HAPI_PDG_State = { rename = "PdgState", mode = -1 }
HAPI_PDG_EventType = { rename = "PdgEventType", mode = -3 }
HAPI_PDG_WorkitemState = { rename = "PdgWorkitemState", mode = -1 }

[bitflags]
HAPI_NodeType = { rename = "auto", mode = -1 }
HAPI_NodeFlags = { rename = "auto", mode = -1 }
HAPI_ErrorCode = { rename = "auto", mode = -1 }

[structs]
#HAPI_AssetInfo = { rename = "auto", builder = false}
#HAPI_NodeInfo{
#HAPI_ParmInfo{
#HAPI_ParmChoiceInfo{
#HAPI_HandleInfo{
#HAPI_HandleBindingInfo{
#HAPI_ObjectInfo{
#HAPI_GeoInfo{
#HAPI_PartInfo{
#HAPI_AttributeInfo{
#HAPI_MaterialInfo{
#HAPI_ImageInfo{
#HAPI_VolumeInfo{
#HAPI_VolumeTileInfo{
#HAPI_VolumeVisualInfo{
#HAPI_CurveInfo{
#HAPI_BoxInfo{
#HAPI_SphereInfo{
#HAPI_PDG_EventInfo{
#HAPI_PDG_WorkitemInfo{
#HAPI_PDG_WorkitemResultInfo{
#HAPI_SessionSyncInfo{