[package]
name = "hapi-rs"
version = "0.1.0"
authors = ["Alex Rusev <hou.alexx@gmail.com>"]
edition = "2018"

[features]
async = []
default = []


[dependencies]
log = "0.4"
strum = "0.20"
strum_macros = "0.20"

[dev-dependencies]
once_cell = "1.5.2"
env_logger = "0.8.2"