[package]
name = "hapi-rs"
version = "0.1.0"
authors = ["Alex Rusev <hou.alexx@gmail.com>"]
edition = "2018"

[features]
async = []
default = []


[dependencies]
#smol = { version = "1.2.4", optional = true }

